import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import UserMenu from '@/components/UserMenu';

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-sans antialiased`}>
        <div className="min-h-screen flex flex-col">
          <header className="w-full flex justify-end items-center p-4">
            <UserMenu />
          </header>
          <main className="flex-1">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
